const Account = require('../models/Account');
const Contact = require('../models/Contact');

// Validate email format
const validateEmail = (email) => {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return emailRegex.test(email);
};

// Validate mobile (exactly 10 digits)
const validateMobile = (mobile) => {
  if (!mobile) return true; // Mobile is optional
  const mobileRegex = /^\d{10}$/;
  return mobileRegex.test(mobile);
};

const createAccount = async (req, res) => {
  try {
    // Validate required fields
    if (!req.body.name || !req.body.mainContact || !req.body.email) {
      return res.status(400).json({ 
        message: 'Name, Main Contact, and Email are required fields' 
      });
    }

    // Validate email format
    if (!validateEmail(req.body.email)) {
      return res.status(400).json({ message: 'Invalid email format' });
    }

    // Validate mobile if provided
    if (req.body.mobile && !validateMobile(req.body.mobile)) {
      return res.status(400).json({ 
        message: 'Mobile number must be exactly 10 digits' 
      });
    }

    // Create account (ID auto-generated by pre-save hook)
    const accountData = {
      ...req.body,
      status: req.body.status || 'Active'
    };

    const account = new Account(accountData);
    const savedAccount = await account.save();

    if (savedAccount) {
      // Auto-create corresponding Contact
      try {
        const contactData = {
          mainContact: savedAccount.mainContact,
          address: savedAccount.address,
          city: savedAccount.city,
          country: savedAccount.country,
          state: savedAccount.state,
          email: savedAccount.email,
          mobile: savedAccount.mobile,
          accountId: savedAccount.accountId,
          accountName: savedAccount.name,
          status: savedAccount.status || 'Active'
        };

        const contact = new Contact(contactData);
        await contact.save();
      } catch (contactError) {
        console.error('Error creating auto-contact:', contactError);
        // Don't fail account creation if contact creation fails
      }

      res.status(201).json(savedAccount);
    } else {
      res.status(500).json({ message: 'Failed to create account' });
    }
  } catch (error) {
    res.status(400).json({ error: error.message });
  }
};

const getAccounts = async (req, res) => {
  try {
    const accounts = await Account.find().sort({ createdAt: -1 });
    if (accounts) {
      res.status(200).json(accounts);
    } else {
      res.status(404).json({ message: 'No accounts found' });
    }
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

const getAccountById = async (req, res) => {
  try {
    const account = await Account.findById(req.params.id);
    if (account) {
      res.status(200).json(account);
    } else {
      res.status(404).json({ message: 'Account not found' });
    }
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

const updateAccount = async (req, res) => {
  try {
    // Validate email if provided
    if (req.body.email && !validateEmail(req.body.email)) {
      return res.status(400).json({ message: 'Invalid email format' });
    }

    // Validate mobile if provided
    if (req.body.mobile && !validateMobile(req.body.mobile)) {
      return res.status(400).json({ 
        message: 'Mobile number must be exactly 10 digits' 
      });
    }

    const account = await Account.findByIdAndUpdate(
      req.params.id,
      req.body,
      { new: true, runValidators: true }
    );
    
    if (account) {
      res.status(200).json(account);
    } else {
      res.status(404).json({ message: 'Account not found' });
    }
  } catch (error) {
    res.status(400).json({ error: error.message });
  }
};

const deleteAccount = async (req, res) => {
  try {
    const account = await Account.findByIdAndDelete(req.params.id);
    if (account) {
      res.status(200).json({ message: 'Account deleted successfully' });
    } else {
      res.status(404).json({ message: 'Account not found' });
    }
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

module.exports = { 
  createAccount, 
  getAccounts, 
  getAccountById, 
  updateAccount, 
  deleteAccount 
};