const Contact = require('../models/Contact');
const Account = require('../models/Account');

// Validate email format
const validateEmail = (email) => {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return emailRegex.test(email);
};

// Validate mobile (exactly 10 digits)
const validateMobile = (mobile) => {
  if (!mobile) return true; // Mobile is optional
  const mobileRegex = /^\d{10}$/;
  return mobileRegex.test(mobile);
};

const createContact = async (req, res) => {
  try {
    // Validate required fields
    if (!req.body.mainContact || !req.body.email) {
      return res.status(400).json({ 
        message: 'Main Contact and Email are required fields' 
      });
    }

    // Validate email format
    if (!validateEmail(req.body.email)) {
      return res.status(400).json({ message: 'Invalid email format' });
    }

    // Validate mobile if provided
    if (req.body.mobile && !validateMobile(req.body.mobile)) {
      return res.status(400).json({ 
        message: 'Mobile number must be exactly 10 digits' 
      });
    }

    // Create contact (ID auto-generated by pre-save hook)
    const contactData = {
      ...req.body,
      status: req.body.status || 'Active'
    };

    const contact = new Contact(contactData);
    const result = await contact.save();
    
    if (result) {
      res.status(201).json(result);
    } else {
      res.status(500).json({ message: 'Failed to create contact' });
    }
  } catch (error) {
    res.status(400).json({ error: error.message });
  }
};

const getContacts = async (req, res) => {
  try {
    const contacts = await Contact.find().sort({ createdAt: -1 });
    if (contacts) {
      res.status(200).json(contacts);
    } else {
      res.status(404).json({ message: 'No contacts found' });
    }
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

const getContactById = async (req, res) => {
  try {
    const contact = await Contact.findById(req.params.id);
    if (contact) {
      res.status(200).json(contact);
    } else {
      res.status(404).json({ message: 'Contact not found' });
    }
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

const updateContact = async (req, res) => {
  try {
    // Validate email if provided
    if (req.body.email && !validateEmail(req.body.email)) {
      return res.status(400).json({ message: 'Invalid email format' });
    }

    // Validate mobile if provided
    if (req.body.mobile && !validateMobile(req.body.mobile)) {
      return res.status(400).json({ 
        message: 'Mobile number must be exactly 10 digits' 
      });
    }

    const contact = await Contact.findByIdAndUpdate(
      req.params.id,
      req.body,
      { new: true, runValidators: true }
    );
    
    if (contact) {
      res.status(200).json(contact);
    } else {
      res.status(404).json({ message: 'Contact not found' });
    }
  } catch (error) {
    res.status(400).json({ error: error.message });
  }
};

const deleteContact = async (req, res) => {
  try {
    const contact = await Contact.findByIdAndDelete(req.params.id);
    if (contact) {
      res.status(200).json({ message: 'Contact deleted successfully' });
    } else {
      res.status(404).json({ message: 'Contact not found' });
    }
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

// Search accounts by name (for dropdown/autocomplete in frontend)
const searchAccounts = async (req, res) => {
  try {
    const searchTerm = req.query.q || '';
    const accounts = await Account.find({
      name: { $regex: searchTerm, $options: 'i' }
    })
      .select('accountId name address city state country email mobile mainContact')
      .limit(20);

    res.status(200).json(accounts);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

// Get contacts for a given accountId
const getContactsByAccount = async (req, res) => {
  try {
    const { accountId } = req.params;
    if (!accountId) return res.status(400).json({ message: 'accountId is required' });
    const contacts = await Contact.find({ accountId }).select('mainContact email mobile department accountId accountName status');
    return res.status(200).json(contacts);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

module.exports = { 
  createContact, 
  getContacts, 
  getContactById, 
  updateContact, 
  deleteContact,
  searchAccounts,
  getContactsByAccount 
};